### PR TITLE
validation and test

### PR DESCRIPTION
**Pull request by ismailakinkunmi**
- Add the following validations:
    For the User model:
    Name must not be blank.
    PostsCounter must be an integer greater than or equal to zero.
- For the Post model:
  Title must not be blank.
  Title must not exceed 250 characters.
  CommentsCounter must be an integer greater than or equal to zero.
  LikesCounter must be an integer greater than or equal to zero.
- Add unit specs for all of your models' methods and validations.

### CODE REVIEW

**Review by rloterh — APPROVED** [review]
Checked!

**Review by rloterh — CHANGES_REQUESTED** [review]
Hi Ak,
 
 While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
 
 ## Invalid Code Review Request
You have submitted a project, whereby
- Checks/ Linters are failing. Kindly ensure that **all** checks are passing.

 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ismailakinkunmi** [comment]
@rloterh thanks

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Ak,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉🌟 

## Highlights 👍
- Unit test and validations properly implemented

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly consider my comments marked **[OPTIONAL]** under this review_

You can also consider:
- [OPTIOANL] Kindly ensure add to your ReadMe details instructions on how to test and or run your project. This will make your ReadMe appear more professional.
<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
